# frozen_string_literal: true

require "rake/testtask"
require "rake/clean"
require "ffi-compiler/compile_task"
require "ffi-compiler/platform"
require "fileutils"
require "etc"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

LIBXCRYPT_SRC_DIR   = File.join(__dir__, "ext", "libxcrypt").freeze
LIBXCRYPT_BUILD_DIR = File.join(__dir__, "tmp", "libxcrypt").freeze
LIBXCRYPT_STATIC    = File.join(LIBXCRYPT_BUILD_DIR, ".libs", "libcrypt.a").freeze

# Arch/OS label used by ffi-compiler for its output subdirectory.
XCRYPT_ARCH_OS = "#{FFI::Platform::ARCH}-#{FFI::Platform::OS}".freeze

# Path to the compiled xcrypt bundle.
XCRYPT_LIB = File.join(
  "lib", "xcrypt", XCRYPT_ARCH_OS,
  FFI::Compiler::Platform.system.map_library_name("xcrypt")
).freeze

# Path to the compiled object file — needs crypt.h which is generated by
# the libxcrypt configure step, so it must depend on libxcrypt:build too.
XCRYPT_OBJ = File.join("lib", "xcrypt", XCRYPT_ARCH_OS, "xcrypt.o").freeze

CLEAN.include("tmp/")
CLOBBER.include(File.dirname(XCRYPT_LIB))

# ---------------------------------------------------------------------------
# libxcrypt — build static library from the submodule
# ---------------------------------------------------------------------------

namespace :libxcrypt do
  desc "Build libxcrypt as a static, position-independent library"
  task :build do
    # The submodule has no pre-generated configure script; generate it first.
    unless File.exist?(File.join(LIBXCRYPT_SRC_DIR, "configure"))
      sh "autoreconf -fiv #{LIBXCRYPT_SRC_DIR}"
    end

    unless File.exist?(LIBXCRYPT_STATIC)
      FileUtils.mkdir_p(LIBXCRYPT_BUILD_DIR)
      sh <<~SH
        cd #{LIBXCRYPT_BUILD_DIR} && \
        #{LIBXCRYPT_SRC_DIR}/configure \
          --enable-static \
          --disable-shared \
          CFLAGS='-fPIC -O2'
      SH
      sh "make -C #{LIBXCRYPT_BUILD_DIR} -j#{Etc.nprocessors}"
    end
  end
end

# ---------------------------------------------------------------------------
# xcrypt extension — compile ext/xcrypt/xcrypt.c and link against libcrypt.a
# ---------------------------------------------------------------------------
#
# ffi-compiler outputs:
#   lib/xcrypt/<arch>-<os>/libxcrypt.bundle  (macOS)
#   lib/xcrypt/<arch>-<os>/libxcrypt.so      (Linux)
#
# The name 'lib/xcrypt/xcrypt' sets ext_dir = 'lib/xcrypt' so the output
# lands in lib/xcrypt/<arch>-<os>/ where FFI::Compiler::Loader can find it.

FFI::Compiler::CompileTask.new("lib/xcrypt/xcrypt") do |t|
  t.source_dirs = ["ext/xcrypt"]

  # crypt.h is generated by ./configure and placed in the build directory.
  t.cflags << "-I#{LIBXCRYPT_BUILD_DIR}"

  # Link ALL symbols from libcrypt.a into the shared library so that
  # Ruby-FFI can bind to them at runtime without any direct C references.
  if FFI::Platform.mac?
    t.ldflags << "-Wl,-force_load,#{LIBXCRYPT_STATIC}"
  else
    t.ldflags << "-Wl,--whole-archive,#{LIBXCRYPT_STATIC},--no-whole-archive"
  end
end

# crypt.h is generated during the libxcrypt configure step, so the .c
# compilation must wait for libxcrypt:build before it can find the header.
Rake::Task[XCRYPT_OBJ].enhance(["libxcrypt:build"])

# Ensure libxcrypt.a is ready before the final link step too.
Rake::Task[XCRYPT_LIB].enhance(["libxcrypt:build"])

desc "Compile the XCrypt native extension"
task compile: XCRYPT_LIB

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

Rake::TestTask.new(:test) do |t|
  t.libs    << "lib"
  t.pattern = "test/**/test_*.rb"
  t.verbose = true
end

task default: [:compile, :test]
